### ISSUE TITLE
file.type is not a function

### ISSUE THREAD

**Issue by atorber** [huan/file-box#78]
When I used puppet-wxwork in wechaty version 0.62.1, I encountered an error：

TypeError: file.type is not a function
    at PuppetService.messageSendFile (/Users/choogoo/workspace/wechaty-mqtt-link/node_modules/wechaty-puppet-service/dist/src/client/puppet-service.js:660:46)

I found the error code. Can you help me solve the problem of file-box?

<img width="697" alt="image" src="https://user-images.githubusercontent.com/19552906/161551786-288c59ed-2732-4779-968c-37a278f2cdcc.png">

I tried the file-box latest and next versions, and the error is the same.

The wechaty-puppet-service version is 0.21.11

When I try to skip the if judgment, the problem is solved. Is this the problem of file-box or wechaty-puppet-service?

<img width="845" alt="image" src="https://user-images.githubusercontent.com/19552906/161552602-b3809990-3cd4-4fe5-aaea-687b61534ab5.png">

**Comment by huan** [comment]
Could you please try the latest version of the ` wechaty-puppet-service@1.19.2` to see if this issue exists?

The FileBox has a breaking change between versions for the `type` because we upgraded to using the Interface instead of the Implementation.

- in the previous version, it's a method (`filebox.type()`), 
- but in the latest version, it's a property (`filebox.type`).

See:

https://github.com/huan/file-box/blob/b345a2210a09f55073edea5194210cf6d1814535/src/file-box.ts#L434-L442

**Comment by atorber** [comment]
Another way of thinking, can I solve it by reducing the version of file box？

I want to  solve the problem under 0.xx, and then try to migrate to 1.xx

**Comment by huan** [comment]
> Another way of thinking, can I solve it by reducing the version of the file box？

Of course. You can lock the FileBox version by `npm install file-box@0.x.y` as you needed.

> I want to solve the problem under 0.xx, and then try to migrate to 1.xx

If you can set up a reproducible repo, I might be able to help by figuring the workable version out for you.
